#!/bin/bash

echo "phifem-bc-geo: solve"
python main.py "$1/phifem-bc-geo"
echo "phifem-bc-geo: error"
python reference_error.py "$1/phifem-bc-geo"
echo "phifem-bc: solve"
python main.py "$1/phifem-bc"
echo "phifem-bc: error"
python reference_error.py "$1/phifem-bc"
echo "phifem-geo: solve"
python main.py "$1/phifem-geo"
echo "phifem-geo: error"
python reference_error.py "$1/phifem-geo"
echo "phiFEM: solve"
python main.py "$1/phifem"
echo "phiFEM: error"
python reference_error.py "$1/phifem"
echo "FEM: solve"
python main_fem.py "$1/fem"
echo "FEM: error"
python reference_error.py "$1/fem"