#!/bin/bash

echo "Reference: solve"
python main_fem.py "$1/reference"
echo "FEM: solve"
python main_fem.py "$1/fem"
echo "FEM: error"
python reference_error.py "$1/fem"
echo "phiFEM: solve"
python main.py "$1/phifem"
echo "phiFEM: error"
python reference_error.py "$1/phifem"
echo "phiFEM-dir: solve"
python main.py "$1/phifem-dir"
echo "phiFEM-dir: error"
python reference_error.py "$1/phifem-dir"
echo "phiFEM-bdy: solve"
python main.py "$1/phifem-bdy"
echo "phiFEM-bdy: error"
python reference_error.py "$1/phifem-bdy"
echo "phiFEM-dir-bdy: solve"
python main.py "$1/phifem-dir-bdy"
echo "phiFEM-dir-bdy: error"
python reference_error.py "$1/phifem-dir-bdy"