#!/bin/bash

echo "Reference: solve"
python main_fem.py "$1/reference" 2> "$1/launch.log"
echo "FEM: solve"
python main_fem.py "$1/fem" 2> "$1/launch.log"
echo "FEM: error"
python reference_error.py "$1/fem" 2> "$1/launch.log"
echo "phiFEM: solve"
python main.py "$1/phifem" 2> "$1/launch.log"
echo "phiFEM: error"
python reference_error.py "$1/phifem" 2> "$1/launch.log"
echo "phiFEM-dir: solve"
python main.py "$1/phifem-dir" 2> "$1/launch.log"
echo "phiFEM-dir: error"
python reference_error.py "$1/phifem-dir" 2> "$1/launch.log"
echo "phiFEM-bdy: solve"
python main.py "$1/phifem-bdy" 2> "$1/launch.log"
echo "phiFEM-bdy: error"
python reference_error.py "$1/phifem-bdy" 2> "$1/launch.log"
echo "phiFEM-dir-bdy: solve"
python main.py "$1/phifem-dir-bdy" 2> "$1/launch.log"
echo "phiFEM-dir-bdy: error"
python reference_error.py "$1/phifem-dir-bdy" 2> "$1/launch.log"